### ISSUE TITLE
デモ動画

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/AMATERASU#23]
https://github.com/user-attachments/assets/90f382c2-6b4a-42c4-9543-887ecc67b6eb

**Comment by iris-s-coon** [comment]
I.R.I.S Bot🤖が以下のラベルを提案し、適用しました：

- enhancement
- documentation

**Comment by iris-s-coon** [comment]
This issue requests a demo video.  Given the repository structure, a demo video should showcase the AMATERASU platform, highlighting its key features: the secure ChatGPT-like interface (Open WebUI), the secure API proxy server (LiteLLM), and the cost management and monitoring platform (Langfuse).

The video should ideally demonstrate the following:

1. **Infrastructure Deployment:** Briefly show the Terraform deployment process using the `spellbook` directory.  This could be a sped-up timelapse of the `terraform init` and `terraform apply` commands for `base-infrastructure`, `open-webui/terraform/main-infrastructure`, and potentially others depending on the chosen scope of the demo.  This part should visually represent the ease of setting up the infrastructure using Terraform and highlight the modular structure of the code.

2. **Open WebUI Interaction:** A significant portion should focus on interacting with the Open WebUI chat interface.  Show how to initiate conversations, use prompt templates (if implemented), and view/search conversation history.  The demo should ideally use different prompts to demonstrate the LLM's capabilities and highlight the user-friendliness of the interface. The security aspect can be subtly emphasized by mentioning the private nature of the platform and its limited access control.

3. **LiteLLM API Interaction (Optional):** If feasible, demonstrate the LiteLLM API by showing a simple API call to the LLM through a separate client application or by showing the API documentation and emphasizing its security features like rate limiting and authentication.  This section could be shorter if the focus is predominantly on the user interface.

4. **Langfuse Monitoring:** Show the Langfuse dashboard, displaying token usage, cost breakdown, and potentially other relevant metrics.  This section should illustrate the platform's ability to track and manage resource consumption, highlighting cost efficiency and control.

5. **Overall Architecture:**  The video could start or end with a visual representation of the system architecture diagram from the README.md, connecting each component's functionality shown in the demonstration.  This helps provide context and summarises the complete platform.

**Specific points to consider for the video:**

* **Target Audience:** Tailor the video's level of technical detail to the target audience. A demo for potential clients should emphasize ease of use and security, while a demo for developers could delve into the code structure and deployment process.
* **Length:** Keep the video concise and engaging.  Aim for a length of 2-5 minutes, focusing on the most important features.
* **Visuals:** Use clear and visually appealing screen recordings.  Avoid showing excessive amounts of code or terminal output unless necessary.
* **Audio:**  Include clear and concise narration explaining the steps and functionality demonstrated.

**Suggestions for improvement:**

The `whitelist.csv` files in several directories appear to contain the same IP addresses.  This suggests a possible inconsistency.  A review and unification of this data would improve maintainability.

The `issue_creator.log` is currently empty. A more informative log could greatly assist with future troubleshooting.  It's recommended to add logging to the deployment scripts and the application itself.


The demo video should demonstrate the entire workflow, from infrastructure deployment to the use of each of the main components. This will provide a clear and compelling demonstration of AMATERASU's capabilities.

**Comment by iris-s-coon** [comment]
## 変更提案

このイシューは、AMATERASUプロジェクトのデモ動画を作成するというものです。提供された情報は、アプリケーションのアーキテクチャ、構成ファイル、およびデプロイメント手順を示しています。しかし、デモ動画を作成するための具体的なコード変更は提供されていません。

そのため、以下の変更を提案します。これは、`app.py`にデモ動画を表示するための簡単な変更であり、より洗練されたデモ動画の作成には、動画編集ソフトウェアなど、追加のツールが必要になります。

まず、`README.md`にデモ動画へのリンクを追加することを提案します。  イシューに添付された動画のURLを`README.md`に埋め込みます。


**変更提案 (README.md):**

```diff
--- a/README.md
+++ b/README.md
@@ -28,6 +28,10 @@
 >AMATERASUは[MOA](https://github.com/Sunwood-ai-labs/MOA)の後継プロジェクトです。各AIサービスを独立したEC2インスタンス上でDocker Composeを用いて実行し、Terraformで簡単にデプロイできるように進化させました。
 
 
+## 🎬 デモ動画
+
+[AMATERASU デモ動画](https://github.com/user-attachments/assets/90f382c2-6b4a-42c4-9543-887ecc67b6eb)
+
 ## 🔒 セキュリティ重視の設計思想
 
 AMATERASUは、セキュリティ要件の厳しい日本企業向けに特化して開発された、プライベートなAIプラットフォーム基盤です。AWS Bedrockを基盤とした安全なLLM活用を実現します：

```

この変更により、ユーザーは`README.md`から直接デモ動画にアクセスできます。


さらに、Streamlitアプリケーション(`app.py`)に動画を埋め込むこともできます。しかし、これは、動画ファイル自体をリポジトリに含める必要があるか、動画が外部ホスティングサービスにある場合、そのURLを提供する必要があります。


**変更提案 (app.py - 動画を埋め込む場合。動画ファイルがリポジトリに存在する必要があります。例えば `demo.mp4`):**

```diff
--- a/app.py
+++ b/app.py
@@ -3,11 +3,16 @@
 
 try:
     with open("README.md", "r", encoding="utf-8") as f:
-        readme_content = f.read()
-    st.markdown(readme_content, unsafe_allow_html=True)
+        st.markdown(f.read(), unsafe_allow_html=True)
 except FileNotFoundError:
     st.error("README.mdが見つかりませんでした。")
+
+try:
+    video_file = open('demo.mp4', 'rb')
+    st.video(video_file)
+    video_file.close()
+except FileNotFoundError:
+    st.error("デモ動画 (demo.mp4) が見つかりませんでした。")
 ```
 
 `issue_creator.log`


この変更により、`README.md`の内容に加えて、`demo.mp4`という名前の動画ファイルがStreamlitアプリケーションに表示されます。 動画ファイルが存在しない場合は、エラーメッセージが表示されます。  `demo.mp4`は、実際にリポジトリに追加する必要があります。


どちらの提案も、より本格的なデモ動画の作成には代替手段となりえます。  本格的なデモ動画を作成する場合は、動画編集ソフトウェアを使用して、AMATERASUの各機能を詳細に説明した動画を作成することをお勧めします。  その動画を、YouTubeなどの動画ホスティングサービスにアップロードし、そのURLを`README.md`に追加すれば、より効果的なデモになります。
